using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LMS.Models;
using LMS.ViewModels;
using LMS.Views.Data;
using LMS.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LMS.Helpers;


namespace LMS
{
    public class QuizController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly IAIQuizService _aiQuizService; // service to generate AI MCQs

        public QuizController(ApplicationDbContext dbContext, IAIQuizService aiQuizService)
        {
            _dbContext = dbContext;
            _aiQuizService = aiQuizService;
        }

        // ===================== Auto Quiz =====================
        [HttpGet]
        public IActionResult AutoQuiz(int courseId)
        {
            var model = new AutoQuizViewModel { CourseId = courseId };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AutoQuiz(AutoQuizViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            // Extract PDF text
            var pdfText = await PdfHelper.ExtractTextAsync(model.PdfFile!.FileName);

            // Generate MCQs using AI
            var mcqs = await _aiQuizService.GenerateMCQsAsync(pdfText);

            // Create Quiz entity
            var quiz = new Quiz
            {
                CourseId = model.CourseId,
                Title = model.Title ?? "AI Generated Quiz",
                Description = model.Description,
                DueDate = DateTime.Now.AddDays(7),
                IsAutoGenerated = true,
                MCQs = mcqs.Select(m => new MCQ
                {
                    Question = m.Question,
                    OptionA = m.OptionA,
                    OptionB = m.OptionB,
                    OptionC = m.OptionC,
                    OptionD = m.OptionD,
                    CorrectAnswer = m.CorrectAnswer,
                    Feedback = m.Feedback
                }).ToList()
            };

            _dbContext.Quizzes.Add(quiz);
            await _dbContext.SaveChangesAsync();

            TempData["Success"] = "AI Quiz generated successfully!";
            return RedirectToAction("Details", "Course", new { id = model.CourseId });
        }

        // ===================== Manual Quiz =====================
        [HttpGet]
        public IActionResult ManualQuiz(int courseId)
        {
            var model = new ManualQuizViewModel { CourseId = courseId };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManualQuiz(ManualQuizViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var quiz = new Quiz
            {
                CourseId = model.CourseId,
                Title = model.Title,
                Description = model.Description,
                DueDate = model.DueDate,
                IsAutoGenerated = false,
                MCQs = model.Questions.Select(q => new MCQ
                {
                    Question = q.Question,
                    OptionA = q.OptionA,
                    OptionB = q.OptionB,
                    OptionC = q.OptionC,
                    OptionD = q.OptionD,
                    OptionE = q.OptionE,
                    CorrectAnswer = q.CorrectAnswer,
                    Feedback = q.Feedback
                }).ToList()
            };

            _dbContext.Quizzes.Add(quiz);
            await _dbContext.SaveChangesAsync();

            TempData["Success"] = "Manual quiz created successfully!";
            return RedirectToAction("Details", "Course", new { id = model.CourseId });
        }

        // ===================== View Quiz for Students =====================
        [HttpGet]
        public async Task<IActionResult> ViewQuiz(int quizId)
        {
            var quiz = await _dbContext.Quizzes
                .Include(q => q.MCQs)
                .FirstOrDefaultAsync(q => q.Id == quizId);

            if (quiz == null) return NotFound();

            // Randomize options for students
            var randomizedMCQs = quiz.MCQs!.Select(q =>
            {
                var options = new List<string> { q.OptionA!, q.OptionB!, q.OptionC!, q.OptionD! };
                if (!string.IsNullOrEmpty(q.OptionE)) options.Add(q.OptionE);

                var shuffled = options.OrderBy(x => Guid.NewGuid()).ToList();
                return new
                {
                    q.Question,
                    Options = shuffled,
                    q.CorrectAnswer,
                    q.Feedback
                };
            }).ToList();

            ViewBag.Quiz = quiz!;
            ViewBag.MCQs = randomizedMCQs!;
            return View();
        }
    }
}