using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models
{
    public class Quiz
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Title { get; set; }

        public string? Description { get; set; }

        [Required]

        public DateTime DueDate { get; set; }

        public bool IsAutoGenerated { get; set; } // true = AI, false = manual

        public int CourseId { get; set; }
        public virtual Course? Course { get; set; }

        public virtual ICollection<MCQ>? MCQs { get; set; }
    }
}